grafana:
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30000  # Grafana on port 30000 (http://<HOST_IP>:30000)
  ingress:
    enabled: false
  image:
    repository: docker.io/grafana/grafana
    tag: "11.1.0"
    registry: ""  # Will be set via --set in workflow
  sidecar:
    dashboards:
      image:
        repository: quay.io/kiwigrid/k8s-sidecar
        tag: "2.1.2"  # Helm Chart default version
        registry: ""  # Will be set via --set in workflow
    datasources:
      image:
        repository: quay.io/kiwigrid/k8s-sidecar
        tag: "2.1.2"  # Helm Chart default version
        registry: ""  # Will be set via --set in workflow

prometheus:
  # Service for direct access to Prometheus (main service)
  service:
    type: NodePort
    nodePort: 30001  # Prometheus on port 30001 (http://<HOST_IP>:30001)
  prometheusSpec:
    retention: 7d
    image:
      repository: quay.io/prometheus/prometheus
      tag: "v2.52.0"
      registry: ""  # Will be set via --set in workflow

alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 30002  # Alertmanager on port 30002 (http://<HOST_IP>:30002)
  image:
    repository: quay.io/prometheus/alertmanager
    tag: "v0.28.0"  # Helm Chart default version
    registry: ""  # Will be set via --set in workflow

prometheusOperator:
  image:
    repository: quay.io/prometheus-operator/prometheus-operator
    tag: "v0.79.2"
    registry: ""  # Will be set via --set in workflow
  prometheusConfigReloader:
    image:
      repository: quay.io/prometheus-operator/prometheus-config-reloader
      tag: "v0.79.2"
      registry: ""  # Will be set via --set in workflow
  configmapReload:
    prometheus:
      image:
        repository: quay.io/prometheus-operator/prometheus-config-reloader
        tag: "v0.79.2"
        registry: ""  # Will be set via --set in workflow
    alertmanager:
      image:
        repository: quay.io/prometheus-operator/prometheus-config-reloader
        tag: "v0.79.2"
        registry: ""  # Will be set via --set in workflow
  admissionWebhooks:
    patch:
      image:
        repository: docker.io/jettech/kube-webhook-certgen
        tag: "v1.5.1"
        registry: ""  # Will be set via --set in workflow

"prometheus-node-exporter":
  image:
    repository: quay.io/prometheus/node-exporter
    tag: "v1.8.2"
    registry: ""  # Will be set via --set in workflow

kube-state-metrics:
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: "v2.10.2"
    registry: ""  # Will be set via --set in workflow

