{{- if .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helper-pod-fix-controller.serviceAccountName" . }}
  namespace: {{ .Values.controller.namespace }}
  labels:
    {{- include "helper-pod-fix-controller.labels" . | nindent 4 }}
{{- end }}

