{{- if .Values.rbac.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRole.name }}
  labels:
    app.kubernetes.io/name: {{ include "cluster-storage.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  # Allow projects to read the central storage ConfigMap
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["{{ .Values.localPathProvisioner.configMap.name }}"]
    verbs: ["get", "list", "watch"]
{{- end }}

